LEARNING_SETUP:
  BATCH_SIZE: 20 #How many images to include in batch when running inference, adjust according to GPU memory
  #OUTPUT_PATH: '/home/feiyan/runs/ucf_generate/'
  OUTPUT_PATH: '/home/feiyan/dhf1k_generate/'
  #OUTPUT_PATH: '/home/feiyan/runs/test_generate_ucf_tmp/'

DATASET_SETUP:  
  DHF1K_PATH: '/data/DHF1K/' #'/home/feiyan/data/DHF1K/' #NULL '/data/DHF1K/'
  UCF_PATH: NULL #'/home/feiyan/data/ucf_sport/' NULL
  HOLLYWOOD_PATH: NULL
  
MODEL_SETUP:
  DECODER : ['d1', 'd2', 'd3']
  CHANNEL_REDUCTION: 1
  INPUT_SIZE: 16
  OUTPUT_SIZE: 1
  SINGLE: [True, True, True]
  FORCE_MULTI: False
  D1_LAST: False
  MODEL_WEIGHTS: '../weights/d1d2d3_S_lt.pth'
  #MODEL_WEIGHTS: '../weights/ucf_d123s.pth'
  #model_path = '../weights/d123s_rc2_rc1T.pth'
  #model_path = '../weights/d123s_rc4_rc1T.pth'